// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TornBot.Bot.Infrastructure;

#nullable disable

namespace TornBot.Bot.Infrastructure.Migrations
{
    [DbContext(typeof(TornbotContext))]
    [Migration("20260804112705_AddRetalState")]
    partial class AddRetalState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TornBot.Bot.Domain.Models.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FactionId")
                        .HasColumnType("integer");

                    b.Property<bool>("HasCompanyAccess")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasFactionAccess")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("LastUsed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TornPlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("TornBot.Bot.Domain.Models.Faction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FactionId")
                        .HasColumnType("integer");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("Factions");
                });

            modelBuilder.Entity("TornBot.Bot.Domain.Models.ModuleConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<JsonDocument>("Config")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("FactionId")
                        .HasColumnType("integer");

                    b.Property<int>("Module")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.ToTable("ModuleConfigs");
                });

            modelBuilder.Entity("TornBot.Bot.Domain.Models.OrganizedCrime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CrimeId")
                        .HasColumnType("integer");

                    b.Property<int?>("FactionId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.ToTable("OrganizedCrimes");
                });

            modelBuilder.Entity("TornBot.Bot.Domain.Models.RetalOpportunity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AttackId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int?>("FactionId")
                        .HasColumnType("integer");

                    b.Property<decimal>("MessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<long>("TargetPlayerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.ToTable("TrackedAttacks");
                });

            modelBuilder.Entity("TornBot.Bot.Domain.Models.ApiKey", b =>
                {
                    b.HasOne("TornBot.Bot.Domain.Models.Faction", null)
                        .WithMany("ApiKeys")
                        .HasForeignKey("FactionId");
                });

            modelBuilder.Entity("TornBot.Bot.Domain.Models.ModuleConfig", b =>
                {
                    b.HasOne("TornBot.Bot.Domain.Models.Faction", null)
                        .WithMany("ModuleConfigs")
                        .HasForeignKey("FactionId");
                });

            modelBuilder.Entity("TornBot.Bot.Domain.Models.OrganizedCrime", b =>
                {
                    b.HasOne("TornBot.Bot.Domain.Models.Faction", null)
                        .WithMany("OrganizedCrimes")
                        .HasForeignKey("FactionId");
                });

            modelBuilder.Entity("TornBot.Bot.Domain.Models.RetalOpportunity", b =>
                {
                    b.HasOne("TornBot.Bot.Domain.Models.Faction", null)
                        .WithMany("TrackedAttacks")
                        .HasForeignKey("FactionId");
                });

            modelBuilder.Entity("TornBot.Bot.Domain.Models.Faction", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("ModuleConfigs");

                    b.Navigation("OrganizedCrimes");

                    b.Navigation("TrackedAttacks");
                });
#pragma warning restore 612, 618
        }
    }
}
